# This file was generated by GoReleaser. DO NOT EDIT.
class HomebrewTap < Formula
  desc ""
  homepage ""
  version "0.3.7"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/atoz-technology/homebrew-tap/releases/download/v0.3.7/homebrew-tap_0.3.7_Darwin_x86_64.tar.gz"
    sha256 "fe17d450813238d4b25834518c7dd84e9acf033c6ec0eeb23a2947837760a8aa"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/atoz-technology/homebrew-tap/releases/download/v0.3.7/homebrew-tap_0.3.7_Linux_x86_64.tar.gz"
    sha256 "eb6ee2dd417d9f9bae4f01f64a8464dcb45728484bd3c0f447bca3ab7b12a9dd"
  end

  def install
    bin.install "homebrew-tap"
  end
end
