# This file was generated by GoReleaser. DO NOT EDIT.
class Pitwall < Formula
  desc ""
  homepage ""
  version "0.4.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/atoz-technology/homebrew-tap/releases/download/v0.4.0/pitwall_0.4.0_darwin_amd64.tar.gz"
    sha256 "552f4a3612ccad25e46365edaf6883ce8d6b1251fe98f2ed145805079d2c6414"
  end
  
  depends_on "libsodium"

  def install
    bin.install "pitwall"
  end
end
